apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: df3g28dtm-python 
  janus-idp.io/tekton: df3g28dtm-python
  backstage.io/kubernetes-id: df3g28dtm-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: df3g28dtm-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml