apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: df3g28dtm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: df3g28dtm-python 
  name: df3g28dtm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: df3g28dtm-python 
